name: flutter_recipe_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^2.0.0+1
  tab_indicator_styler: ^2.0.0
  cupertino_icons: ^1.0.8
  simple_icons: ^10.1.3
  icon_decoration: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
